### ISSUE TITLE
[Request] RTM Mac Notification widget App

### ISSUE THREAD

**Issue by pheonixia** [hanschen/Remember-The-Milk-Simple#1]
Can someone make or link me to a RTM Mac Notification widget App that appears in the Notification Center and connects to the internet?

If not, can someone link me to a dummies guide on how to make my own widgets for the notification center in Mac? I have no knowledge of how to code, but I am willing to learn if someone links me to a resource. 

Thank you.

**Comment by hanschen** [comment]
This isn't really the right place for this question (I doubt it's going to be seen by many people), you could try to ask in the RTM forum instead. https://www.rememberthemilk.com/forums/help/
